# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idcomentario', models.AutoField(db_column='idComentario', primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fechacomentario', models.DateField(db_column='fechaComentario')),
            ],
            options={
                'managed': False,
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idcuenta', models.AutoField(db_column='idCuenta', primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=255, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'Cuenta',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('idinteraccion', models.AutoField(db_column='idInteraccion', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'Interaccion',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.AutoField(db_column='idNotificacion', primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'Notificacion',
            },
        ),
        migrations.CreateModel(
            name='Tipointeraccion',
            fields=[
                ('idtipointeraccion', models.AutoField(db_column='idTipoInteraccion', primary_key=True, serialize=False)),
                ('nombreinteraccion', models.CharField(db_column='nombreInteraccion', max_length=255, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'TipoInteraccion',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idvideo', models.AutoField(db_column='idVideo', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('ubicacionvideo', models.CharField(db_column='ubicacionVideo', max_length=255)),
                ('ubicacionthumbnail', models.CharField(db_column='ubicacionThumbnail', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechasubida', models.DateField(db_column='fechaSubida')),
            ],
            options={
                'managed': False,
                'db_table': 'Video',
            },
        ),
    ]
