# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasBuscados',
            fields=[
                ('idmasbuscados', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('titulo', models.TextField(db_column='titulo')),
                ('ubicacionthumbnail', models.TextField(db_column='ubicacionThumbnail')),
                ('ubicacionvideo', models.TextField(db_column='ubicacionVideo')),
                ('usuario', models.TextField(db_column='usuario')),
                ('visitas', models.IntegerField(db_column='visitas')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'MasBuscados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasVistos',
            fields=[
                ('idmasvistos', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('titulo', models.TextField(db_column='titulo')),
                ('ubicacionthumbnail', models.TextField(db_column='ubicacionThumbnail')),
                ('ubicacionvideo', models.TextField(db_column='ubicacionVideo')),
                ('usuario', models.TextField(db_column='usuario')),
                ('visitas', models.IntegerField(db_column='visitas')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'MasVistos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacionesOrdenadas',
            fields=[
                ('idnotificacionordenada', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idnotificacion', models.AutoField(db_column='idNotificacion', primary_key=True)),
                ('contenido', models.CharField(max_length=255)),
                ('idcuenta', models.IntegerField(db_column='idCuenta')),
                ('fechanotificacion', models.DateTimeField(db_column='fechaNotificacion')),
            ],
            options={
                'db_table': 'NotificacionesOrdenadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recientes',
            fields=[
                ('idrecientes', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('titulo', models.TextField(db_column='titulo')),
                ('ubicacionthumbnail', models.TextField(db_column='ubicacionThumbnail')),
                ('ubicacionvideo', models.TextField(db_column='ubicacionVideo')),
                ('usuario', models.TextField(db_column='usuario')),
                ('visitas', models.IntegerField(db_column='visitas')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'Recientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('idthumbnail', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('titulo', models.TextField(db_column='titulo')),
                ('ubicacionthumbnail', models.TextField(db_column='ubicacionThumbnail')),
                ('ubicacionvideo', models.TextField(db_column='ubicacionVideo')),
                ('usuario', models.TextField(db_column='usuario')),
                ('visitas', models.IntegerField(db_column='visitas')),
                ('fecha', models.DateField(db_column='fecha')),
            ],
            options={
                'db_table': 'Thumbnail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoDetalle',
            fields=[
                ('idvideodetalle', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('idvideo', models.IntegerField(db_column='idVideo')),
                ('titulo', models.TextField(db_column='titulo')),
                ('ubicacionthumbnail', models.TextField(db_column='ubicacionThumbnail')),
                ('ubicacionvideo', models.TextField(db_column='ubicacionVideo')),
                ('usuario', models.TextField(db_column='usuario')),
                ('visitas', models.IntegerField(db_column='visitas')),
                ('fecha', models.DateField(db_column='fecha')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VideoDetalle',
                'managed': False,
            },
        ),
    ]
